name: CI

on:
  pull_request:
  push:
    branches: 
      - staging
      - trying

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check if hello.txt present
      run: test -f hello.txt
